### ISSUE TITLE
Exception in thread "Craft Scheduler Thread

### ISSUE THREAD

**Issue by infect** [phaed420/SimpleClans#275]
Getting these Errors since a few minutes. No clue what the trigger was. Trying to figure it out..

20:16:51 INFO]: This server is running CraftBukkit version git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
[20:16:51 INFO]: Checking version, please wait...
[20:16:51 INFO]: You are running the latest version

20:13:05 WARN]: org.apache.commons.lang.UnhandledException: Plugin SimpleClans v2.5.4 generated an exception while executing task 96
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

[20:14:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin SimpleClans v2.5.4 generated an exception while executing task 96
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

20:15:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin SimpleClans v2.5.4 generated an exception while executing task 96
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

**Comment by phaed420** [comment]
Let me know if this did it.

**Comment by infect** [comment]
Well. Since your update i didnt have any errors. Seems to work now. I'll post an update if anyting new comes up. Thanks
